name: Complete

on:
  workflow_run:
    workflows: [Skip]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
  # all-jobs-complete:
  #   runs-on: ubuntu-latest
  #   if: |
  #     !github.event.pull_request.draft && 
  #     !cancelled()
  #   steps:
  #     - run: |
  #         echo "This job does nothing"
  #         echo ${{ needs.e2e.result }}