name: Needs test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  changed-files:
    runs-on: ubuntu-latest
    outputs:
      frontend_any_changed: ${{ steps.changed-files.outputs.frontend_any_changed }}
      backend_any_changed: ${{ steps.changed-files.outputs.backend_any_changed }}
    steps:
      - run: echo ${{ github.job }}
      - id: changed-files
        run: |
          echo "::set-output name=frontend_any_changed::true"
          echo "::set-output name=backend_any_changed::false"

  lint-js:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.job }}
  lint-py:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.job }}
    if: ${{ false }}

  lints-complete:
    runs-on: ubuntu-latest
    needs:
      - lint-js
      - lint-py
    if: |
      always() &&
      !contains(needs.*.result, 'failure') &&
      !contains(needs.*.result, 'cancelled')
    steps:
      - run: echo ${{ github.job }}

  post-lint:
    runs-on: ubuntu-latest
    needs:
      - lints-complete
    if: ${{ !failure() && !cancelled() }}
    steps:
      - run: echo ${{ github.job }}

  test-py:
    runs-on: ubuntu-latest
    needs:
      - lints-complete
      - changed-files
    if: | 
      !failure() && !cancelled() && ${{ needs.changed-files.outputs.backend_any_changed == 'true' }}
    steps:
      - run: echo ${{ github.job }}

  test-js:
    runs-on: ubuntu-latest
    needs:
      - lints-complete
      - changed-files
    if: | 
      !failure() && !cancelled() && ${{ needs.changed-files.outputs.frontend_any_changed == 'true' }}
    steps:
      - run: echo ${{ github.job }}
