name: Needs test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

concurrency:
  # A single workflow at a time per PR
  group: needs-${{ github.ref }}
  # When new changes are pushed, other workflows on the PR are cancelled.
  cancel-in-progress: true

jobs:
  changed-files:
    runs-on: ubuntu-latest
    outputs:
      frontend_any_changed: ${{ steps.changed-files.outputs.frontend_any_changed }}
      backend_any_changed: ${{ steps.changed-files.outputs.backend_any_changed }}
    steps:
      - run: echo ${{ github.job }}
      - id: changed-files
        run: |
          echo "::set-output name=frontend_any_changed::true"
          echo "::set-output name=backend_any_changed::false"

  lint-js:
    runs-on: ubuntu-latest
    needs:
      - changed-files
    steps:
      - run: echo ${{ github.job }}
    if: ${{ needs.changed-files.outputs.frontend_any_changed == 'true' }}

  lint-py:
    runs-on: ubuntu-latest
    needs:
      - changed-files
    steps:
      - run: echo ${{ github.job }}
    if: ${{ needs.changed-files.outputs.backend_any_changed == 'true' }}

  test-py:
    runs-on: ubuntu-latest
    needs:
      - lint-js
      - lint-py
      - changed-files
    if: | 
      always() && !cancelled() &&
      !failure('lint-js') &&
      !failure('lint-py') &&
      (success('lint-js') || success('lint-py')) &&
      needs.changed-files.outputs.backend_any_changed == 'true'
    steps:
      - run: echo ${{ github.job }}

  test-js:
    runs-on: ubuntu-latest
    needs:
      - lint-js
      - lint-py
      - changed-files
    if: | 
      always() && !cancelled() &&
      !failure('lint-js') &&
      !failure('lint-py') &&
      (success('lint-js') || success('lint-py')) &&
      needs.changed-files.outputs.frontend_any_changed == 'true'
    steps:
      - run: echo ${{ github.job }}
      - run: exit 0

  e2e:
    runs-on: ubuntu-latest
    needs:
      - test-py
      - test-js
      - changed-files
    if: | 
      always() && !cancelled() &&
      !failure('test-js') &&
      !failure('test-py') &&
      (needs.changed-files.outputs.backend_any_changed == 'true' || needs.changed-files.outputs.frontend_any_changed == 'true')
    steps:
      - run: echo ${{ github.job }}
