name: Needs test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  lint-js:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.job }}
  lint-py:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.job }}

  lints-complete:
    runs-on: ubuntu-latest
    needs:
      - lint-js
      - lint-py
    if: |
      always() &&
      !contains(needs.*.result, 'failure') &&
      !contains(needs.*.result, 'cancelled')

  post-lint:
    runs-on: ubuntu-latest
    needs:
      - lints-complete
