name: Outputs test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

concurrency:
  # A single workflow at a time per PR
  group: needs-${{ github.ref }}
  # When new changes are pushed, other workflows on the PR are cancelled.
  cancel-in-progress: true


jobs:
  job1:
    outputs:
      json: ${{ steps.step2.outputs.json }}
      more-json: ${{ steps.step1.outputs.json }}
      tag: ${{ steps.set-output.outputs.tag }}
    runs-on: ubuntu-latest
    steps:
      - name: Docker metadata
        id: step1
        uses: docker/metadata-action@v4
        with:
          images: |
            denhai/job1
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=sha
      - id: step2
        run: |
          echo 'json=${{steps.step1.outputs.json}}' >> $GITHUB_OUTPUT

      - uses: actions/github-script@v6
        id: set-output
        with:
          script: |
            const tags = `${{steps.step1.outputs.tags}}`;
            console.log(tags);
            const tag = tags.split('\n').at(-1);
            core.setOutput("tag", tag);   
  job2:
    runs-on: ubuntu-latest
    needs:
      - job1
    steps:
      # - run: |
      #     echo ${{needs.job1.outputs.json}}
      # - run: |
      #     echo '${{needs.job1.outputs.json}}'
      - run: |
          echo '${{needs.job1.outputs.json}}' | jq ".tags"
      - run: |
          echo ${{needs.job1.outputs.tag}}
