name: Skip

on:
  push:
    branches: [main]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      # https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull_request
      # opened, synchronize, or reopened are the defaults.
      - ready_for_review
    branches: [main]

  workflow_dispatch:

concurrency:
  # A single workflow at a time per PR
  group: needs-${{ github.ref }}
  # When new changes are pushed, other workflows on the PR are cancelled.
  cancel-in-progress: true

jobs:
  changed-files:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    outputs:
      frontend_any_changed: ${{ steps.changed-files.outputs.frontend_any_changed }}
      backend_any_changed: ${{ steps.changed-files.outputs.backend_any_changed }}
    steps:
      - run: echo ${{ github.job }}
      - id: changed-files
        run: |
          echo "::set-output name=frontend_any_changed::true"
          echo "::set-output name=backend_any_changed::false"

  lint-js:
    runs-on: ubuntu-latest
    needs:
      - changed-files
    steps:
      - run: echo ${{ github.job }}
    if: ${{ !github.event.pull_request.draft }}

  lint-py:
    runs-on: ubuntu-latest
    needs:
      - changed-files
    steps:
      - run: echo ${{ github.job }}
      # - run: exit 1
    if: ${{ !github.event.pull_request.draft }}

  test-py:
    runs-on: ubuntu-latest
    needs:
      - lint-js
      - lint-py
      - changed-files
    if: |
      !github.event.pull_request.draft &&
      !failure('lint-js') &&
      !failure('lint-py') &&
      (success('lint-js') || success('lint-py'))
    steps:
      - run: echo ${{ github.job }}

  test-js:
    runs-on: ubuntu-latest
    needs:
      - lint-js
      - lint-py
      - changed-files
    if: |
      !github.event.pull_request.draft &&
      !failure('lint-js') &&
      !failure('lint-py') &&
      (success('lint-js') || success('lint-py'))
    steps:
      - run: echo ${{ github.job }}
      - run: exit 0

  e2e:
    runs-on: ubuntu-latest
    needs:
      - test-py
      - test-js
      - changed-files
    if: |
      !github.event.pull_request.draft &&
      !failure('test-js') &&
      !failure('test-py') &&
      (success('test-js') || success('test-py'))
    steps:
      - run: echo ${{ github.job }}

  all-jobs-complete:
    runs-on: ubuntu-latest
    needs:
      - e2e
      - test-js
      - test-py
      - lint-py
      - lint-js
    if: |
      !github.event.pull_request.draft && 
      !cancelled()
    steps:
      - run: |
          passed=${{
            (needs.e2e.result == 'success' || needs.e2e.result == 'skipped') &&
            (needs.test-js.result == 'success' || needs.test-js.result == 'skipped') &&
            (needs.test-py.result == 'success' || needs.test-py.result == 'skipped') &&
            (needs.lint-py.result == 'success' || needs.lint-py.result == 'skipped') &&
            (needs.lint-js.result == 'success' || needs.lint-js.result == 'skipped')
          }}
          [ "$passed" = "true" ]
